const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type,apikey","Access-Control-Allow-Methods":"GET,POST,PUT,OPTIONS"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=utf-8",...cors}})}
function html(){return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSL Greenhouse</title><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><style>body{margin:0;background:#0b1220;color:#eef2ff;font:15px system-ui}.wrap{max-width:1200px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.card{background:#151f33;border:1px solid #293653;border-radius:18px;padding:18px}.v{font-size:28px;font-weight:700;margin-top:8px}.online{color:#65e6a0}.danger{color:#ff7474}button{padding:10px 14px;border:0;border-radius:10px;cursor:pointer;margin:4px}canvas{max-height:330px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}</style></head><body><main class="wrap"><div class="top"><h1>🌱 NSL Greenhouse</h1><div id="esp">ESP32: --</div></div><div class="grid"><div class="card">🌱 Đất A<div id="a" class="v">--</div></div><div class="card">🌱 Đất B<div id="b" class="v">--</div></div><div class="card">🌡️ Nhiệt độ<div id="t" class="v">--</div></div><div class="card">💧 Độ ẩm KK<div id="h" class="v">--</div></div><div class="card">💨 MQ-2<div id="s" class="v">--</div></div><div class="card">🌧️ Mưa<div id="r" class="v">--</div></div><div class="card">💦 Bơm<div id="p" class="v">--</div></div><div class="card">🌀 Quạt<div id="f" class="v">--</div></div><div class="card">🚨 Cảnh báo<div id="al" class="v">--</div></div></div><section class="card" style="margin-top:14px"><h2>Lịch sử</h2><canvas id="chart"></canvas></section><section class="card" style="margin-top:14px"><h2>Điều khiển</h2><button onclick="cmd('pump',true)">💦 Bật bơm</button><button onclick="cmd('pump',false)">Tắt bơm</button><button onclick="cmd('fan',true)">🌀 Bật quạt</button><button onclick="cmd('fan',false)">Tắt quạt</button></section></main><script>
let chart; async function get(p){let r=await fetch('/api/'+p);if(!r.ok)throw Error();return r.json()}
async function refresh(){try{let d=await get('latest');a.textContent=d.soil_a+'%';b.textContent=d.soil_b+'%';t.textContent=d.temperature==null?'--':d.temperature+' °C';h.textContent=d.humidity==null?'--':d.humidity+' %';s.textContent=d.smoke;r.textContent=d.raining?'ĐANG MƯA':'KHÔ';p.textContent=d.pump?'BẬT':'TẮT';f.textContent=d.fan?'BẬT':'TẮT';al.textContent=d.alarm?'NGUY HIỂM':'BÌNH THƯỜNG';let age=(Date.now()-new Date(d.created_at).getTime())/1000;esp.textContent=age<30?'🟢 ESP32 ONLINE':'🔴 ESP32 OFFLINE';esp.className=age<30?'online':'danger'}catch(e){esp.textContent='🔴 SERVER/ESP32 OFFLINE'}}
async function history(){try{let d=await get('history');let labels=d.map(x=>new Date(x.created_at).toLocaleTimeString());if(chart)chart.destroy();chart=new Chart(document.getElementById('chart'),{type:'line',data:{labels,datasets:[{label:'Đất A %',data:d.map(x=>x.soil_a)},{label:'Đất B %',data:d.map(x=>x.soil_b)},{label:'Nhiệt °C',data:d.map(x=>x.temperature)}]},options:{responsive:true}})}catch(e){}}
async function cmd(device,on){await fetch('/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device,on})});refresh()} refresh();history();setInterval(refresh,5000);setInterval(history,15000);
</script></body></html>`}
async function sb(env,path,init={}){const h=new Headers(init.headers||{});h.set("apikey",env.SUPABASE_ANON_KEY);h.set("Authorization","Bearer "+env.SUPABASE_ANON_KEY);if(init.body)h.set("Content-Type","application/json");return fetch(env.SUPABASE_URL+path,{...init,headers:h})}
export default {async fetch(req,env){
if(req.method==="OPTIONS")return new Response(null,{headers:cors});
const u=new URL(req.url);
if(u.pathname==="/")return new Response(html(),{headers:{"content-type":"text/html;charset=utf-8"}});
if(u.pathname==="/health")return json({ok:true,service:"nsl-greenhouse-worker",time:new Date().toISOString()});
if(!env.SUPABASE_URL||!env.SUPABASE_ANON_KEY)return json({error:"Supabase secrets are not configured"},503);
const auth=req.headers.get("Authorization")||"";
async function requireAuth(){if(!auth.startsWith("Bearer "))return false;const r=await fetch(env.SUPABASE_URL+"/auth/v1/user",{headers:{apikey:env.SUPABASE_ANON_KEY,Authorization:auth}});return r.ok}
async function proxy(path,init={}){return sb(env,path,init)}
if(u.pathname==="/api/device/heartbeat"&&req.method==="POST"){
 const b=await req.json().catch(()=>({})); const row={device_id:b.device_id||"esp32-01",created_at:new Date().toISOString()};
 const r=await proxy("/rest/v1/greenhouse_heartbeats",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(row)}); return json({ok:r.ok},r.status)}
if(u.pathname==="/api/device/sensors"&&req.method==="POST"){
 const b=await req.json(); const row={device_id:b.device_id||"esp32-01",soil_a:b.soil_a,soil_b:b.soil_b,temperature:b.temperature,humidity:b.humidity,smoke:b.smoke,rain:b.rain,raining:!!b.raining,pump:!!b.pump,fan:!!b.fan,alarm:!!b.alarm};
 const r=await proxy("/rest/v1/greenhouse_readings",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(row)}); return json({ok:r.ok},r.status)}
if(u.pathname==="/api/status"){let r=await proxy("/rest/v1/greenhouse_heartbeats?select=*&order=created_at.desc&limit=1");let d=await r.json();let x=d?.[0];return json({online:!!x&&Date.now()-new Date(x.created_at).getTime()<30000,last_seen:x?.created_at||null,device_id:x?.device_id||null})}
if(u.pathname==="/api/latest"){let r=await proxy("/rest/v1/greenhouse_readings?select=*&order=created_at.desc&limit=1");return new Response(r.body,{status:r.status,headers:{"content-type":"application/json",...cors}})}
if(u.pathname==="/api/history"){let r=await proxy("/rest/v1/greenhouse_readings?select=created_at,soil_a,soil_b,temperature,humidity,smoke,rain,raining,pump,fan,alarm&order=created_at.desc&limit=200");let d=await r.json();return json(Array.isArray(d)?d.reverse():d,r.status)}
if(u.pathname==="/api/settings"&&req.method==="GET"){let r=await proxy("/rest/v1/greenhouse_settings?select=*&id=eq.1&limit=1");return new Response(r.body,{status:r.status,headers:{"content-type":"application/json",...cors}})}
if(u.pathname==="/api/settings/update"&&req.method==="POST"){if(!(await requireAuth()))return json({error:"Unauthorized"},401);const b=await req.json();const allowed={};for(const k of ["soil_dry_threshold","high_temperature","smoke_threshold","rain_threshold","auto_mode","force_pump","force_fan"])if(k in b)allowed[k]=b[k];allowed.updated_at=new Date().toISOString();let r=await proxy("/rest/v1/greenhouse_settings?id=eq.1",{method:"PATCH",headers:{"Prefer":"return=minimal"},body:JSON.stringify(allowed)});return json({ok:r.ok},r.status)}
if(u.pathname==="/api/control/pump"&&req.method==="POST"||u.pathname==="/api/control/fan"&&req.method==="POST"){if(!(await requireAuth()))return json({error:"Unauthorized"},401);const device=u.pathname.includes("pump")?"pump":"fan";const b=await req.json().catch(()=>({}));if(typeof b.on!=="boolean")return json({error:"on must be boolean"},400);let row={device,state:b.on,created_at:new Date().toISOString()};let r=await proxy("/rest/v1/greenhouse_commands",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(row)});return json({ok:r.ok,command:row},r.status)}
if(u.pathname==="/api/commands"&&req.method==="GET"){let r=await proxy("/rest/v1/greenhouse_commands?select=*&order=id.desc&limit=50");return new Response(r.body,{status:r.status,headers:{"content-type":"application/json",...cors}})}
if(u.pathname==="/api/commands/pending"&&req.method==="GET"){let r=await proxy("/rest/v1/greenhouse_commands?select=*&acknowledged_at=is.null&order=id.asc&limit=20");return new Response(r.body,{status:r.status,headers:{"content-type":"application/json",...cors}})}
if(u.pathname.match(/^\/api\/commands\/\d+\/ack$/)&&req.method==="POST"){const id=u.pathname.split("/")[3];let r=await proxy("/rest/v1/greenhouse_commands?id=eq."+id,{method:"PATCH",headers:{"Prefer":"return=minimal"},body:JSON.stringify({acknowledged_at:new Date().toISOString()})});return json({ok:r.ok},r.status)}
if(u.pathname==="/api/command"&&req.method==="POST"){if(!(await requireAuth()))return json({error:"Unauthorized"},401);const b=await req.json();if(!["pump","fan"].includes(b.device)||typeof b.on!=="boolean")return json({error:"invalid command"},400);let row={device:b.device,state:b.on,created_at:new Date().toISOString()};let r=await proxy("/rest/v1/greenhouse_commands",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(row)});return json({ok:r.ok,queued:row},r.status)}
return json({error:"Not found"},404)}}