const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,content-type,apikey","Access-Control-Allow-Methods":"GET,POST,PUT,OPTIONS"};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=utf-8",...cors}})}
function html(){return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NSL Greenhouse</title><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><style>body{margin:0;background:#0b1220;color:#eef2ff;font:15px system-ui}.wrap{max-width:1200px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:14px}.card{background:#151f33;border:1px solid #293653;border-radius:18px;padding:18px}.v{font-size:28px;font-weight:700;margin-top:8px}.online{color:#65e6a0}.danger{color:#ff7474}button{padding:10px 14px;border:0;border-radius:10px;cursor:pointer;margin:4px}canvas{max-height:330px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}</style></head><body><main class="wrap"><div class="top"><h1>🌱 NSL Greenhouse</h1><div id="esp">ESP32: --</div></div><div class="grid"><div class="card">🌱 Đất A<div id="a" class="v">--</div></div><div class="card">🌱 Đất B<div id="b" class="v">--</div></div><div class="card">🌡️ Nhiệt độ<div id="t" class="v">--</div></div><div class="card">💧 Độ ẩm KK<div id="h" class="v">--</div></div><div class="card">💨 MQ-2<div id="s" class="v">--</div></div><div class="card">🌧️ Mưa<div id="r" class="v">--</div></div><div class="card">💦 Bơm<div id="p" class="v">--</div></div><div class="card">🌀 Quạt<div id="f" class="v">--</div></div><div class="card">🚨 Cảnh báo<div id="al" class="v">--</div></div></div><section class="card" style="margin-top:14px"><h2>Lịch sử</h2><canvas id="chart"></canvas></section><section class="card" style="margin-top:14px"><h2>Điều khiển</h2><button onclick="cmd('pump',true)">💦 Bật bơm</button><button onclick="cmd('pump',false)">Tắt bơm</button><button onclick="cmd('fan',true)">🌀 Bật quạt</button><button onclick="cmd('fan',false)">Tắt quạt</button></section></main><script>
let chart; async function get(p){let r=await fetch('/api/'+p);if(!r.ok)throw Error();return r.json()}
async function refresh(){try{let d=await get('latest');a.textContent=d.soil_a+'%';b.textContent=d.soil_b+'%';t.textContent=d.temperature==null?'--':d.temperature+' °C';h.textContent=d.humidity==null?'--':d.humidity+' %';s.textContent=d.smoke;r.textContent=d.raining?'ĐANG MƯA':'KHÔ';p.textContent=d.pump?'BẬT':'TẮT';f.textContent=d.fan?'BẬT':'TẮT';al.textContent=d.alarm?'NGUY HIỂM':'BÌNH THƯỜNG';let age=(Date.now()-new Date(d.created_at).getTime())/1000;esp.textContent=age<30?'🟢 ESP32 ONLINE':'🔴 ESP32 OFFLINE';esp.className=age<30?'online':'danger'}catch(e){esp.textContent='🔴 SERVER/ESP32 OFFLINE'}}
async function history(){try{let d=await get('history');let labels=d.map(x=>new Date(x.created_at).toLocaleTimeString());if(chart)chart.destroy();chart=new Chart(document.getElementById('chart'),{type:'line',data:{labels,datasets:[{label:'Đất A %',data:d.map(x=>x.soil_a)},{label:'Đất B %',data:d.map(x=>x.soil_b)},{label:'Nhiệt °C',data:d.map(x=>x.temperature)}]},options:{responsive:true}})}catch(e){}}
async function cmd(device,on){await fetch('/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({device,on})});refresh()} refresh();history();setInterval(refresh,5000);setInterval(history,15000);
</script></body></html>`}
async function sb(env,path,init={}){const h=new Headers(init.headers||{});h.set("apikey",env.SUPABASE_ANON_KEY);h.set("Authorization","Bearer "+env.SUPABASE_ANON_KEY);if(init.body)h.set("Content-Type","application/json");return fetch(env.SUPABASE_URL+path,{...init,headers:h})}
export default {async fetch(req,env){if(req.method==="OPTIONS")return new Response(null,{headers:cors});const u=new URL(req.url);if(u.pathname==="/health")return json({ok:true,service:"nsl-greenhouse-worker"});if(u.pathname==="/")return new Response(html(),{headers:{"content-type":"text/html;charset=utf-8"}});if(!env.SUPABASE_URL||!env.SUPABASE_ANON_KEY)return json({error:"Configure Supabase secrets first"},503);
if(u.pathname==="/api/latest"){let r=await sb(env,"/rest/v1/greenhouse_readings?select=*&order=created_at.desc&limit=1");return new Response(r.body,{status:r.status,headers:{"content-type":"application/json",...cors}})}
if(u.pathname==="/api/history"){let r=await sb(env,"/rest/v1/greenhouse_readings?select=created_at,soil_a,soil_b,temperature,humidity,smoke,rain,raining,pump,fan,alarm&order=created_at.desc&limit=100");let d=await r.json();return json(Array.isArray(d)?d.reverse():d,r.status)}
if(u.pathname==="/api/settings"&&req.method==="GET"){let r=await sb(env,"/rest/v1/greenhouse_settings?select=*&id=eq.1&limit=1");return new Response(r.body,{status:r.status,headers:{"content-type":"application/json",...cors}})}
if(u.pathname==="/api/command"&&req.method==="POST"){let b=await req.json();if(!["pump","fan"].includes(b.device)||typeof b.on!=="boolean")return json({error:"invalid command"},400);let row={device:b.device,state:b.on,created_at:new Date().toISOString()};let r=await sb(env,"/rest/v1/greenhouse_commands",{method:"POST",headers:{"Prefer":"return=minimal"},body:JSON.stringify(row)});return json({ok:r.ok,queued:row},r.status)}
return json({error:"Not found"},404)}}