create table if not exists greenhouse_readings (id bigint generated by default as identity primary key, created_at timestamptz not null default now(), device_id text default 'esp32-01', soil_a int, soil_b int, temperature real, humidity real, smoke int, rain int, raining boolean default false, pump boolean default false, fan boolean default false, alarm boolean default false);
create table if not exists greenhouse_settings (id int primary key default 1, soil_dry_threshold int default 35, high_temperature real default 32, smoke_threshold int default 1800, rain_threshold int default 1800, auto_mode boolean default true, force_pump boolean default false, force_fan boolean default false, updated_at timestamptz default now());
insert into greenhouse_settings(id) values(1) on conflict(id) do nothing;
create table if not exists greenhouse_commands (id bigint generated by default as identity primary key, created_at timestamptz not null default now(), device text not null, state boolean not null, acknowledged_at timestamptz);
alter table greenhouse_readings enable row level security;
alter table greenhouse_settings enable row level security;
alter table greenhouse_commands enable row level security;
create policy "read readings" on greenhouse_readings for select using (true);
create policy "insert readings" on greenhouse_readings for insert with check (true);
create policy "read settings" on greenhouse_settings for select using (true);
create policy "read commands" on greenhouse_commands for select using (true);
create policy "insert commands" on greenhouse_commands for insert with check (true);

create table if not exists greenhouse_heartbeats (id bigint generated by default as identity primary key, created_at timestamptz not null default now(), device_id text not null default 'esp32-01');
alter table greenhouse_heartbeats enable row level security;
create policy "read heartbeats" on greenhouse_heartbeats for select using (true);
create policy "insert heartbeats" on greenhouse_heartbeats for insert with check (true);

create policy "update settings" on greenhouse_settings for update using (true) with check (true);
