-- NSL Greenhouse cloud database (Supabase/PostgreSQL)
create table if not exists greenhouse_readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  soil_a integer not null,
  soil_b integer not null,
  temperature numeric,
  humidity numeric,
  smoke integer,
  rain integer,
  raining boolean not null default false,
  pump boolean not null default false,
  fan boolean not null default false,
  alarm boolean not null default false
);

create index if not exists greenhouse_readings_created_at_idx
on greenhouse_readings(created_at desc);

create table if not exists greenhouse_settings (
  id integer primary key default 1,
  updated_at timestamptz not null default now(),
  soil_dry_threshold integer not null default 35,
  high_temperature numeric not null default 32,
  smoke_threshold integer not null default 1800,
  rain_threshold integer not null default 1800,
  auto_mode boolean not null default true,
  force_pump boolean not null default false,
  force_fan boolean not null default false,
  constraint only_one_settings_row check (id = 1)
);

insert into greenhouse_settings(id) values (1)
on conflict (id) do nothing;

alter table greenhouse_readings enable row level security;
alter table greenhouse_settings enable row level security;

create policy "public can read readings"
on greenhouse_readings for select
to anon using (true);

create policy "public can insert readings"
on greenhouse_readings for insert
to anon with check (true);

create policy "public can read settings"
on greenhouse_settings for select
to anon using (true);

create policy "public can update settings"
on greenhouse_settings for update
to anon using (true) with check (true);

-- Dashboard chỉ cần đọc/sửa các bảng trên.
-- Với hệ thống triển khai thật, nên thay public policies bằng Supabase Auth
-- và giới hạn quyền ghi bằng user/service role phù hợp.
